/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banksystem;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.Vector;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer
 */
public class CreateNewAccount extends javax.swing.JFrame {

    Connection conn1, conn2;
    PreparedStatement select, selectRates, selectMoneyStock, updateMoneyStock, insertSaving, insertFixed;
    PreparedStatement insertAccountInterest;

    String accountNumber = "";
    double saving_children,saving_normal,saving_adults,fixed_3_months,fixed_6_months,fixed_1_year,fixed_2_years,fixed_5_years;
    double interestRate;
    double initialDeposit;

    int[] durations = {3,6,12,24,60};
    LocalDate endDate;

    double moneyStock, newMoneyStock;

    /**
     * Creates new form CreateNewAccount
     */
    public CreateNewAccount() {
        initComponents();
        newAccountUsername.setText(User.getUsername());
        newAccountPassword.setText(User.getPassword());
        timeDurationLabel.setVisible(false);
        newAccountDuration.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu19 = new javax.swing.JMenu();
        jMenu20 = new javax.swing.JMenu();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenu21 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        newAccountUsername = new javax.swing.JTextField();
        newAccountAccountNumber = new javax.swing.JTextField();
        checkAccountNumberButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        newAccountTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        newAccountInterestRate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        newAccountInitialDeposit = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        newAccountAccountType = new javax.swing.JComboBox<>();
        timeDurationLabel = new javax.swing.JLabel();
        newAccountDuration = new javax.swing.JComboBox<>();
        newAccountPassword = new javax.swing.JPasswordField();
        newAccountBackButton = new javax.swing.JButton();
        newAccountCancelButton = new javax.swing.JButton();
        newAccountCreateAccountButton = new javax.swing.JButton();
        newAccountHomeButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        newAccountTable2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem1.setText("Home");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem2.setText("Exit");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Accounts");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem6.setText("Create account");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem7.setText("Deposit money");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem8.setText("Take money");
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Loans");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu3);

        jMenu5.setText("Transactions");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem4.setText("Transfer money");
        jMenu5.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem5.setText("Transfer Statement");
        jMenu5.add(jMenuItem5);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Interests");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Register");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem3.setText("Register");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem3);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Profile");
        jMenu8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu8);

        jMenu4.setText("File");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem9.setText("Home");
        jMenu4.add(jMenuItem9);

        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem10.setText("Exit");
        jMenu4.add(jMenuItem10);

        jMenuBar2.add(jMenu4);

        jMenu9.setText("Accounts");
        jMenu9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem11.setText("Create account");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem11);

        jMenuItem12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem12.setText("Deposit money");
        jMenu9.add(jMenuItem12);

        jMenuItem13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem13.setText("Take money");
        jMenu9.add(jMenuItem13);

        jMenuBar2.add(jMenu9);

        jMenu10.setText("Loans");
        jMenu10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar2.add(jMenu10);

        jMenu11.setText("Transactions");
        jMenu11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem14.setText("Transfer money");
        jMenu11.add(jMenuItem14);

        jMenuItem15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem15.setText("Transfer Statement");
        jMenu11.add(jMenuItem15);

        jMenuBar2.add(jMenu11);

        jMenu12.setText("Interests");
        jMenu12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar2.add(jMenu12);

        jMenu13.setText("Register");
        jMenu13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem16.setText("Register");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem16);

        jMenuBar2.add(jMenu13);

        jMenu14.setText("Profile");
        jMenu14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar2.add(jMenu14);

        jMenu15.setText("File");
        jMenu15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem17.setText("Home");
        jMenu15.add(jMenuItem17);

        jMenuItem18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem18.setText("Exit");
        jMenu15.add(jMenuItem18);

        jMenuBar3.add(jMenu15);

        jMenu16.setText("Accounts");
        jMenu16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem19.setText("Create account");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuItem19);

        jMenuItem20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem20.setText("Deposit money");
        jMenu16.add(jMenuItem20);

        jMenuItem21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem21.setText("Take money");
        jMenu16.add(jMenuItem21);

        jMenuBar3.add(jMenu16);

        jMenu17.setText("Loans");
        jMenu17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar3.add(jMenu17);

        jMenu18.setText("Transactions");
        jMenu18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem22.setText("Transfer money");
        jMenu18.add(jMenuItem22);

        jMenuItem23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem23.setText("Transfer Statement");
        jMenu18.add(jMenuItem23);

        jMenuBar3.add(jMenu18);

        jMenu19.setText("Interests");
        jMenu19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar3.add(jMenu19);

        jMenu20.setText("Register");
        jMenu20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem24.setText("Register");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu20.add(jMenuItem24);

        jMenuBar3.add(jMenu20);

        jMenu21.setText("Profile");
        jMenu21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar3.add(jMenu21);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 102, 255)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("username");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("password");

        newAccountUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        newAccountUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAccountUsernameActionPerformed(evt);
            }
        });

        newAccountAccountNumber.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        newAccountAccountNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAccountAccountNumberActionPerformed(evt);
            }
        });

        checkAccountNumberButton.setBackground(new java.awt.Color(153, 255, 102));
        checkAccountNumberButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkAccountNumberButton.setText("Check ");
        checkAccountNumberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAccountNumberButtonActionPerformed(evt);
            }
        });

        newAccountTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        newAccountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "NIC Number", "Birthday", "Telephone No.", "Occupation"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(newAccountTable);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Account Type");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Interest Rate");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Initial Deposit");

        newAccountInterestRate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("%");

        newAccountInitialDeposit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Rs.");

        newAccountAccountType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        newAccountAccountType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saving Account", "Fixed Account" }));
        newAccountAccountType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAccountAccountTypeActionPerformed(evt);
            }
        });

        timeDurationLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        timeDurationLabel.setText("Time Duration");

        newAccountDuration.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        newAccountDuration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3 months", "6 months", "1 year", "2 years", "5 years" }));

        newAccountBackButton.setBackground(new java.awt.Color(0, 204, 0));
        newAccountBackButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        newAccountBackButton.setForeground(new java.awt.Color(255, 255, 255));
        newAccountBackButton.setText("Back");
        newAccountBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAccountBackButtonActionPerformed(evt);
            }
        });

        newAccountCancelButton.setBackground(new java.awt.Color(255, 0, 0));
        newAccountCancelButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        newAccountCancelButton.setForeground(new java.awt.Color(255, 255, 255));
        newAccountCancelButton.setText("Cancel");
        newAccountCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAccountCancelButtonActionPerformed(evt);
            }
        });

        newAccountCreateAccountButton.setBackground(new java.awt.Color(0, 0, 153));
        newAccountCreateAccountButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        newAccountCreateAccountButton.setForeground(new java.awt.Color(255, 255, 255));
        newAccountCreateAccountButton.setText("Create Account");
        newAccountCreateAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAccountCreateAccountButtonActionPerformed(evt);
            }
        });

        newAccountHomeButton.setBackground(new java.awt.Color(255, 255, 51));
        newAccountHomeButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        newAccountHomeButton.setText("Home");
        newAccountHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAccountHomeButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("(Rs.1000.00 or more)");

        newAccountTable2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        newAccountTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account Number", "Money Amount", "Start Date", "End Date", "Last Exchange", "Annual Interest Rate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(newAccountTable2);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Account Number");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(newAccountBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addComponent(newAccountCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newAccountCreateAccountButton)
                .addGap(115, 115, 115))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(newAccountHomeButton, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel1))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(newAccountDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(newAccountAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(newAccountInterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel6)))
                                                .addGap(0, 265, Short.MAX_VALUE)))))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(newAccountUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(newAccountPassword)
                                    .addComponent(checkAccountNumberButton)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(timeDurationLabel)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(32, 32, 32)
                                                .addComponent(jLabel7))
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(newAccountInitialDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(newAccountAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)))
                        .addGap(44, 44, 44))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(newAccountUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(newAccountHomeButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(newAccountAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(newAccountPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeDurationLabel)
                            .addComponent(newAccountDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkAccountNumberButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(newAccountInterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newAccountAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newAccountInitialDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newAccountBackButton)
                    .addComponent(newAccountCancelButton)
                    .addComponent(newAccountCreateAccountButton))
                .addContainerGap(251, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void updateMoneyStock(){
        boolean endOfFile = false;
        try{
            FileInputStream fileIn = new FileInputStream("MoneyStock.txt");
            ObjectInputStream inputFile = new ObjectInputStream(fileIn);
            FileOutputStream fileOut = new FileOutputStream("MoneyStock.txt");
            ObjectOutputStream outputFile = new ObjectOutputStream(fileOut);

            while(!endOfFile){
                moneyStock = inputFile.readDouble(); 
            }
            System.out.println("Money Stock : "+moneyStock);
            newMoneyStock = moneyStock + initialDeposit;
            System.out.println("New Money Stock : "+newMoneyStock);
            outputFile.writeDouble(newMoneyStock);

            inputFile.close();
            outputFile.close();
        }
        catch(EOFException f){
            endOfFile = true;
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void checkAccountNumberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAccountNumberButtonActionPerformed
        
        try{

            String username = newAccountUsername.getText().trim();
            String password = String.valueOf(newAccountPassword.getPassword()).trim();

            Class.forName("com.mysql.cj.jdbc.Driver");
            conn1 = DriverManager.getConnection("jdbc:mysql://localhost:3307/bank_system","root","");
            select = conn1.prepareStatement("select * from clients");
            ResultSet rs = select.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            int c = rsmd.getColumnCount();
            DefaultTableModel df = (DefaultTableModel) newAccountTable.getModel();
            df.setRowCount(0);

            Vector v = new Vector();

            while(rs.next()){
                for(int a=1; a<=c; a++){
                    if(rs.getString("username").equals(username) && rs.getString("password").equals(password)){

                        accountNumber = rs.getString("accountnumber");
                        System.out.println("Account Number : "+accountNumber);

                        v.add(rs.getString("name"));
                        v.add(rs.getString("address"));
                        v.add(rs.getString("NIC"));
                        v.add(rs.getDate("birthday"));
                        v.add(rs.getString("telephone"));
                        v.add(rs.getString("occupation"));

                        Date today = Date.valueOf(LocalDate.now()); 
                        Date birthday =  rs.getDate("birthday");
                        long difference = today.getTime() - birthday.getTime();
                        TimeUnit time = TimeUnit.DAYS; 
                        long days = time.convert(difference, TimeUnit.MILLISECONDS);
                        long age = days/365;
                        
                        selectRates = conn1.prepareStatement("select * from interest_rates");
                        ResultSet rs2 = selectRates.executeQuery();
                        ResultSetMetaData rsmd2 = rs.getMetaData();
                        int c2 = rsmd2.getColumnCount();
                        while(rs2.next()){
                            for(int b=1; b<=c2; b++){     
                                saving_children = rs2.getDouble("saving_children");
                                saving_normal = rs2.getDouble("saving_normal");
                                saving_adults = rs2.getDouble("saving_adults");
                                fixed_3_months = rs2.getDouble("fixed_3_months");
                                fixed_6_months = rs2.getDouble("fixed_6_months");
                                fixed_1_year = rs2.getDouble("fixed_1_year");
                                fixed_2_years = rs2.getDouble("fixed_2_years");
                                fixed_5_years = rs2.getDouble("fixed_5_years");
                            }
                        }        
                        
                        if(newAccountAccountType.getSelectedIndex()==0){
                            if(age<18) interestRate = saving_children;
                            else if(age<60) interestRate = saving_normal;
                            else if(age>=60) interestRate = saving_children;
                            else JOptionPane.showMessageDialog(null, "You haven't entered your birthday correctly while registration. Please meet one of our managers");
                        }      
                        if(newAccountAccountType.getSelectedIndex()==1){
                            int duration = newAccountDuration.getSelectedIndex();
                            if(duration==0) interestRate = fixed_3_months;
                            else if(duration==1) interestRate = fixed_6_months;
                            else if(duration==2) interestRate = fixed_1_year;
                            else if(duration==3) interestRate = fixed_2_years;
                            else if(duration==4) interestRate = fixed_5_years;
                        }     
                        newAccountInterestRate.setText(interestRate+"");

                        break;
                    }
                }
            }
            df.addRow(v);
            newAccountAccountNumber.setText(accountNumber);
            if(accountNumber.isEmpty()) JOptionPane.showMessageDialog(null, "Invalid username or password.");

            newAccountAccountType.setEnabled(false);
            newAccountDuration.setEnabled(false);
            newAccountInterestRate.setEditable(false);  
            newAccountAccountNumber.setEditable(false);  

        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        }
        catch(Exception f){
            JOptionPane.showMessageDialog(null, f);
            System.out.println(f);
        }
    }//GEN-LAST:event_checkAccountNumberButtonActionPerformed

    private void newAccountHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAccountHomeButtonActionPerformed
        new ClientSector().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_newAccountHomeButtonActionPerformed

    private void newAccountBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAccountBackButtonActionPerformed
        new ClientSector().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_newAccountBackButtonActionPerformed

    private void newAccountAccountTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAccountAccountTypeActionPerformed
        if(newAccountAccountType.getSelectedIndex()==1){
            timeDurationLabel.setVisible(true);
            newAccountDuration.setVisible(true);
        }
    }//GEN-LAST:event_newAccountAccountTypeActionPerformed

    private void newAccountAccountNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAccountAccountNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newAccountAccountNumberActionPerformed

    private void newAccountCreateAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAccountCreateAccountButtonActionPerformed
        String initialDepositText = newAccountInitialDeposit.getText().trim();
        if(initialDepositText.isEmpty()){
            JOptionPane.showMessageDialog(null, "You have to deposit Rs.1000.00 or more initially.");
        }
        else{
            initialDeposit = Double.parseDouble(initialDepositText);   
            if(initialDeposit<1000.0){
                JOptionPane.showMessageDialog(null, "Initial deposit should be Rs.1000.00 or more.");
            }
            else{
                initialDeposit = initialDeposit;

                try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn2 = DriverManager.getConnection("jdbc:mysql://localhost:3307/bank_system",
                                                                                  "root","");
            if(newAccountAccountType.getSelectedIndex()==0){
                insertSaving = conn2.prepareStatement("insert into saving_accounts (account_number,money_amount,start_date,last_exchange,annual_interest_rate,state) values (?,?,?,?,?,?)");
                insertSaving.setString(1,accountNumber);
                insertSaving.setDouble(2,initialDeposit);
                insertSaving.setDate(3,Date.valueOf(LocalDate.now()));
                insertSaving.setDouble(4,initialDeposit);
                insertSaving.setDouble(5,interestRate);
                insertSaving.setString(6,"pending");
                insertSaving.executeUpdate();
            }
            else if(newAccountAccountType.getSelectedIndex()==1){
                insertFixed = conn2.prepareStatement("insert into fixed_deposits (account_number,money_amount,start_date,end_date,last_exchange,annual_interest_rate,state) values (?,?,?,?,?,?,?)");
                insertFixed.setString(1,accountNumber);
                insertFixed.setDouble(2,initialDeposit);
                insertFixed.setDate(3,Date.valueOf(LocalDate.now()));
                if(newAccountDuration.getSelectedIndex()==0)  endDate = LocalDate.now().plusMonths(3); 
                if(newAccountDuration.getSelectedIndex()==1)  endDate = LocalDate.now().plusMonths(6); 
                if(newAccountDuration.getSelectedIndex()==2)  endDate = LocalDate.now().plusMonths(12); 
                if(newAccountDuration.getSelectedIndex()==3)  endDate = LocalDate.now().plusMonths(24); 
                if(newAccountDuration.getSelectedIndex()==4)  endDate = LocalDate.now().plusMonths(60); 
                insertFixed.setDate(4,Date.valueOf(endDate));
                insertFixed.setDouble(5,initialDeposit);
                insertFixed.setDouble(6,interestRate);
                insertFixed.setString(7,"pending");
                insertFixed.executeUpdate();
            }
            JOptionPane.showMessageDialog(this, "Account created successfully.");
            //updateMoneyStock();

            DefaultTableModel df3 = (DefaultTableModel) newAccountTable2.getModel();
            df3.setRowCount(0);

            Vector v3 = new Vector();
            v3.add(accountNumber);
            v3.add(initialDeposit);
            v3.add(LocalDate.now());
            if(newAccountAccountType.getSelectedIndex()==0)  v3.add("");
            else if(newAccountAccountType.getSelectedIndex()==1)  v3.add(endDate);
            v3.add(initialDeposit);
            v3.add(interestRate);
            df3.addRow(v3);

            selectMoneyStock = conn2.prepareStatement("select * from bank_money_stock");
            ResultSet rs4 = selectMoneyStock.executeQuery();
            while(rs4.next()){
                moneyStock = rs4.getDouble("money_stock");
                newMoneyStock = moneyStock + initialDeposit;
            }
            updateMoneyStock = conn2.prepareStatement("update bank_money_stock set money_stock=?");
            updateMoneyStock.setDouble(1, newMoneyStock);
            updateMoneyStock.executeUpdate();

            insertAccountInterest = conn2.prepareStatement("insert into account_interest (account_number, last_date, accountType) values (?,?,?)");
            insertAccountInterest.setInt(1,Integer.valueOf(accountNumber));
            insertAccountInterest.setDate(2,Date.valueOf(LocalDate.now()));
            if(newAccountAccountType.getSelectedIndex()==0){
                insertAccountInterest.setString(3, "saving");
            }
            else if(newAccountAccountType.getSelectedIndex()==1){
                insertAccountInterest.setString(3, "fixed");
            }
            insertAccountInterest.executeUpdate();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        }
        catch(Exception f){
            JOptionPane.showMessageDialog(null, f);
            System.out.println(f);
        }

            }
        }

        
    }//GEN-LAST:event_newAccountCreateAccountButtonActionPerformed

    private void newAccountUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAccountUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newAccountUsernameActionPerformed

    private void newAccountCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAccountCancelButtonActionPerformed
        newAccountUsername.setText("");
        newAccountPassword.setText("");
        newAccountAccountNumber.setText("");
        newAccountInterestRate.setText("");
        newAccountInitialDeposit.setText("");
        newAccountAccountType.setSelectedIndex(0);
        newAccountDuration.setSelectedIndex(0);
        timeDurationLabel.setVisible(false);
        newAccountDuration.setVisible(false);
         
        DefaultTableModel df4 = (DefaultTableModel) newAccountTable.getModel();
        df4.setRowCount(0);
        DefaultTableModel df5 = (DefaultTableModel) newAccountTable2.getModel();
        df5.setRowCount(0);
    }//GEN-LAST:event_newAccountCancelButtonActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        new CreateNewAccount().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new RegistrationForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        new CreateNewAccount().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        new RegistrationForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        new CreateNewAccount().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        new RegistrationForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static
            void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public
                    void run() {
                new CreateNewAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkAccountNumberButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField newAccountAccountNumber;
    private javax.swing.JComboBox<String> newAccountAccountType;
    private javax.swing.JButton newAccountBackButton;
    private javax.swing.JButton newAccountCancelButton;
    private javax.swing.JButton newAccountCreateAccountButton;
    private javax.swing.JComboBox<String> newAccountDuration;
    private javax.swing.JButton newAccountHomeButton;
    private javax.swing.JTextField newAccountInitialDeposit;
    private javax.swing.JTextField newAccountInterestRate;
    private javax.swing.JPasswordField newAccountPassword;
    private javax.swing.JTable newAccountTable;
    private javax.swing.JTable newAccountTable2;
    private javax.swing.JTextField newAccountUsername;
    private javax.swing.JLabel timeDurationLabel;
    // End of variables declaration//GEN-END:variables
}
