/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banksystem;

import java.sql.*;
import java.text.DecimalFormat;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer
 */
public class LoanPayReturn extends javax.swing.JFrame {

    /**
     * Creates new form LoanCheck
     */

    Connection conn1, conn2;
    PreparedStatement select, selectLoan, selectStock, updateStock, updateLoan;

    private int accountNumber;
    private double max_amount;
    private double money_stock;
    private double amount;
    private String loanType;
    private int durationInMonths;
    private double annualInterestRate;
    private double totalReturn;
    private double monthlyReturn;
    private double paidAmount;
    private double remainingAmount;
    private String state;

    public LoanPayReturn() {
        initComponents();
        payReturnUsername.setText(User.getUsername());
        payReturnPassword.setText(User.getPassword());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        applyLoanBackButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        payReturnHomeButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        payReturnUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        payReturnPassword = new javax.swing.JPasswordField();
        payReturnCheckButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        payReturnAccountNumber = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        payReturnTable = new javax.swing.JTable();
        payReturnBackButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        payReturnPaymentAmount = new javax.swing.JTextField();
        payReturnCancelButton = new javax.swing.JButton();
        payReturnPayButton = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Username");

        applyLoanBackButton.setBackground(new java.awt.Color(255, 51, 51));
        applyLoanBackButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        applyLoanBackButton.setForeground(new java.awt.Color(255, 255, 255));
        applyLoanBackButton.setText("Back");
        applyLoanBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyLoanBackButtonActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 102, 255)));

        payReturnHomeButton.setBackground(new java.awt.Color(255, 255, 51));
        payReturnHomeButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        payReturnHomeButton.setText("Home");
        payReturnHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payReturnHomeButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Pay Loan Return");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Username");

        payReturnUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Password");

        payReturnPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payReturnPasswordActionPerformed(evt);
            }
        });

        payReturnCheckButton.setBackground(new java.awt.Color(153, 255, 51));
        payReturnCheckButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        payReturnCheckButton.setText("Check");
        payReturnCheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payReturnCheckButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Account Number");

        payReturnAccountNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        payReturnTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        payReturnTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Amount", "Duration", "Interest Rate", "Total Return", "Monthly Return", "Paid Amount", "Remaining Amount", "State"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Float.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(payReturnTable);

        payReturnBackButton.setBackground(new java.awt.Color(255, 51, 51));
        payReturnBackButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        payReturnBackButton.setForeground(new java.awt.Color(255, 255, 255));
        payReturnBackButton.setText("Back");
        payReturnBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payReturnBackButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Amount of Payment");

        payReturnPaymentAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        payReturnCancelButton.setBackground(new java.awt.Color(0, 0, 255));
        payReturnCancelButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        payReturnCancelButton.setForeground(new java.awt.Color(255, 255, 255));
        payReturnCancelButton.setText("Cancel");
        payReturnCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payReturnCancelButtonActionPerformed(evt);
            }
        });

        payReturnPayButton.setBackground(new java.awt.Color(0, 204, 51));
        payReturnPayButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        payReturnPayButton.setForeground(new java.awt.Color(255, 255, 255));
        payReturnPayButton.setText("Pay");
        payReturnPayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payReturnPayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(payReturnHomeButton)
                        .addGap(207, 207, 207)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(payReturnCheckButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(payReturnUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                    .addComponent(payReturnPassword))
                                .addGap(62, 62, 62)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(payReturnAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(payReturnPaymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(payReturnBackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(payReturnCancelButton)
                .addGap(183, 183, 183)
                .addComponent(payReturnPayButton)
                .addGap(154, 154, 154))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(payReturnHomeButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payReturnUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(payReturnAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(payReturnPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(payReturnCheckButton)
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(payReturnPaymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payReturnBackButton)
                    .addComponent(payReturnCancelButton)
                    .addComponent(payReturnPayButton))
                .addGap(200, 200, 200))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void payReturnHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payReturnHomeButtonActionPerformed
        new ClientSector().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_payReturnHomeButtonActionPerformed

    private void payReturnPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payReturnPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payReturnPasswordActionPerformed

    private void payReturnCheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payReturnCheckButtonActionPerformed
        try{

            String username = payReturnUsername.getText().trim();
            String password = String.valueOf(payReturnPassword.getPassword()).trim();

            Class.forName("com.mysql.cj.jdbc.Driver");
            conn1 = DriverManager.getConnection("jdbc:mysql://localhost:3307/bank_system","root","");
            select = conn1.prepareStatement("select * from clients");
            ResultSet rs = select.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            int c = rsmd.getColumnCount();

            while(rs.next()){
                for(int a=1; a<=c; a++){
                    if(rs.getString("username").equals(username) && rs.getString("password").equals(password)){

                        String accountNumberText = rs.getString("accountnumber");
                        System.out.println("Account Number : "+accountNumberText);
                        
                        accountNumber = Integer.valueOf(accountNumberText);

                        payReturnAccountNumber.setText(accountNumberText);
                      
                    }
                }
            }

            selectLoan = conn1.prepareStatement("select * from loans");
            ResultSet rs2 = selectLoan.executeQuery();
            ResultSetMetaData rsmd2 = rs2.getMetaData();
            int c2 = rsmd2.getColumnCount();
            DefaultTableModel df = (DefaultTableModel) payReturnTable.getModel();
            df.setRowCount(0);

            Vector v = new Vector();

            while(rs2.next()){
                for(int a=1; a<=c2; a++){
                    if(rs2.getInt("account_number")==accountNumber){

                        amount = rs2.getDouble("amount");
                        durationInMonths = rs2.getInt("duration");
                        annualInterestRate = rs2.getDouble("interest_rate");
                        paidAmount = rs2.getDouble("paid_amount");
                        state = rs2.getString("state");

                        Loan loan = new Loan(accountNumber, amount, durationInMonths, annualInterestRate, paidAmount, state);

                        v.add(loan.getAmount());
                        v.add(loan.getDurationInMonths());
                        v.add(loan.getAnnualInterestRate());
                        v.add(loan.getTotalReturn());
                        v.add(loan.getMonthlyReturn());
                        v.add(loan.getPaidAmount());
                        v.add(loan.getRemainingAmount());
                        v.add(loan.getState());
                      
                    }
                }
            }
            df.addRow(v);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        }
        catch(Exception f){
            JOptionPane.showMessageDialog(null, f);
            System.out.println(f);
        }
    }//GEN-LAST:event_payReturnCheckButtonActionPerformed

    private void applyLoanBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyLoanBackButtonActionPerformed
        new ClientSector().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_applyLoanBackButtonActionPerformed

    private void payReturnBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payReturnBackButtonActionPerformed
        new ClientSector().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_payReturnBackButtonActionPerformed

    private void payReturnCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payReturnCancelButtonActionPerformed
        payReturnUsername.setText("");
        payReturnPassword.setText("");
        payReturnAccountNumber.setText("");
        payReturnPaymentAmount.setText("");
        DefaultTableModel df4 = (DefaultTableModel) payReturnTable.getModel();
        df4.setRowCount(0);
    }//GEN-LAST:event_payReturnCancelButtonActionPerformed

    private void payReturnPayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payReturnPayButtonActionPerformed
        
        double payment = Double.valueOf(payReturnPaymentAmount.getText().trim());
        paidAmount += payment;
        remainingAmount -= payment; 

        Vector v2 = new Vector();

        Loan loan2 = new Loan(accountNumber, amount, durationInMonths, annualInterestRate, paidAmount, state);

        try{

            Class.forName("com.mysql.cj.jdbc.Driver");
            conn2 = DriverManager.getConnection("jdbc:mysql://localhost:3307/bank_system","root","");

            updateLoan = conn2.prepareStatement("update loans set paid_amount = ? where account_number = ?");
            updateLoan.setDouble(1,paidAmount);
            updateLoan.setInt(2,accountNumber);
            updateLoan.executeUpdate();

            selectStock = conn2.prepareStatement("select * from bank_money_stock");
            ResultSet rs3 = selectStock.executeQuery();
            ResultSetMetaData rsmd3 = rs3.getMetaData();
            int c3 = rsmd3.getColumnCount();

            while(rs3.next()){
                for(int b=1; b<=c3; b++){
                    money_stock = rs3.getDouble("money_stock");
                }
            }

            money_stock += payment;

            updateStock = conn2.prepareStatement("update bank_money_stock set money_stock=?");
            updateStock.setDouble(1, money_stock);
            updateStock.executeUpdate();

        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        }
        catch(Exception f){
            JOptionPane.showMessageDialog(null, f);
            System.out.println(f);
        }

        v2.add(loan2.getAmount());
        v2.add(loan2.getDurationInMonths());
        v2.add(loan2.getAnnualInterestRate());
        v2.add(loan2.getTotalReturn());
        v2.add(loan2.getMonthlyReturn());
        v2.add(loan2.getPaidAmount());
        v2.add(loan2.getRemainingAmount());
        v2.add(loan2.getState());

        DefaultTableModel df3 = (DefaultTableModel) payReturnTable.getModel();
        df3.setRowCount(0);
        df3.addRow(v2);

        JOptionPane.showMessageDialog(null, "Your return payment is successfully done.");

    }//GEN-LAST:event_payReturnPayButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static
            void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanPayReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanPayReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanPayReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanPayReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public
                    void run() {
                new LoanPayReturn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyLoanBackButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField payReturnAccountNumber;
    private javax.swing.JButton payReturnBackButton;
    private javax.swing.JButton payReturnCancelButton;
    private javax.swing.JButton payReturnCheckButton;
    private javax.swing.JButton payReturnHomeButton;
    private javax.swing.JPasswordField payReturnPassword;
    private javax.swing.JButton payReturnPayButton;
    private javax.swing.JTextField payReturnPaymentAmount;
    private javax.swing.JTable payReturnTable;
    private javax.swing.JTextField payReturnUsername;
    // End of variables declaration//GEN-END:variables
}
