/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banksystem;

import java.sql.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author Acer
 */
public class LoanCheck extends javax.swing.JFrame {

    /**
     * Creates new form LoanCheck
     */

    Connection conn1;
    PreparedStatement select, selectLoan;

    private int accountNumber;
    private double max_amount;
    private double money_stock;
    private double amount;
    private String loanType;
    private int durationInMonths;
    private double annualInterestRate;
    private double totalReturn;
    private double monthlyReturn;
    private double paidAmount;
    private double remainingAmount;
    private String state;

    public LoanCheck() {
        initComponents();
        checkLoanUsername.setText(User.getUsername());
        checkLoanPassword.setText(User.getPassword());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        applyLoanBackButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        checkLoanHomeButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        checkLoanUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        checkLoanPassword = new javax.swing.JPasswordField();
        checkLoanCheckButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        checkLoanAccountNumber = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        checkLoanTable = new javax.swing.JTable();
        checkLoanBackButton = new javax.swing.JButton();
        checkLoanCancelButton = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Username");

        applyLoanBackButton.setBackground(new java.awt.Color(255, 51, 51));
        applyLoanBackButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        applyLoanBackButton.setForeground(new java.awt.Color(255, 255, 255));
        applyLoanBackButton.setText("Back");
        applyLoanBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyLoanBackButtonActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 102, 255)));

        checkLoanHomeButton.setBackground(new java.awt.Color(255, 255, 51));
        checkLoanHomeButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkLoanHomeButton.setText("Home");
        checkLoanHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLoanHomeButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("My Current Loan");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Username");

        checkLoanUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Password");

        checkLoanPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLoanPasswordActionPerformed(evt);
            }
        });

        checkLoanCheckButton.setBackground(new java.awt.Color(153, 255, 51));
        checkLoanCheckButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkLoanCheckButton.setText("Check");
        checkLoanCheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLoanCheckButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Account Number");

        checkLoanAccountNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        checkLoanTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkLoanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Amount", "Duration", "Interest Rate", "Total Return", "Monthly Returnl", "Paid Amount", "Remaining Amount", "State"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Float.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(checkLoanTable);

        checkLoanBackButton.setBackground(new java.awt.Color(255, 51, 51));
        checkLoanBackButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkLoanBackButton.setForeground(new java.awt.Color(255, 255, 255));
        checkLoanBackButton.setText("Back");
        checkLoanBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLoanBackButtonActionPerformed(evt);
            }
        });

        checkLoanCancelButton.setBackground(new java.awt.Color(0, 0, 255));
        checkLoanCancelButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkLoanCancelButton.setForeground(new java.awt.Color(255, 255, 255));
        checkLoanCancelButton.setText("Cancel");
        checkLoanCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLoanCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(checkLoanBackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(checkLoanCancelButton)
                .addGap(250, 250, 250))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(checkLoanUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                    .addComponent(checkLoanPassword))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(165, 165, 165)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(133, 133, 133)
                                        .addComponent(checkLoanAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(checkLoanCheckButton)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(checkLoanHomeButton)
                        .addGap(207, 207, 207)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(checkLoanHomeButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkLoanUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(checkLoanPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(checkLoanAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addComponent(checkLoanCheckButton)
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(280, 280, 280))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkLoanBackButton)
                            .addComponent(checkLoanCancelButton))
                        .addGap(196, 196, 196))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkLoanHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLoanHomeButtonActionPerformed
        new ClientSector().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_checkLoanHomeButtonActionPerformed

    private void checkLoanPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLoanPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkLoanPasswordActionPerformed

    private void checkLoanCheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLoanCheckButtonActionPerformed
        try{

            String username = checkLoanUsername.getText().trim();
            String password = String.valueOf(checkLoanPassword.getPassword()).trim();

            Class.forName("com.mysql.cj.jdbc.Driver");
            conn1 = DriverManager.getConnection("jdbc:mysql://localhost:3307/bank_system","root","");

            select = conn1.prepareStatement("select * from clients");
            ResultSet rs = select.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            int c = rsmd.getColumnCount();

            while(rs.next()){
                for(int a=1; a<=c; a++){
                    if(rs.getString("username").equals(username) && rs.getString("password").equals(password)){

                        String accountNumberText = rs.getString("accountnumber");
                        System.out.println("Account Number : "+accountNumberText);
                        accountNumber = Integer.valueOf(accountNumberText);

                        checkLoanAccountNumber.setText(accountNumberText);
                      
                    }
                }
            }

            selectLoan = conn1.prepareStatement("select * from loans");
            ResultSet rs2 = selectLoan.executeQuery();
            ResultSetMetaData rsmd2 = rs2.getMetaData();
            int c2 = rsmd2.getColumnCount();
            DefaultTableModel df = (DefaultTableModel) checkLoanTable.getModel();
            df.setRowCount(0);

            Vector v = new Vector();

            while(rs2.next()){
                for(int a=1; a<=c2; a++){
                    if(rs2.getInt("account_number") == accountNumber){

                        amount = rs2.getDouble("amount");
                        durationInMonths = rs2.getInt("duration");
                        annualInterestRate = rs2.getDouble("interest_rate");
                        paidAmount = rs2.getDouble("paid_amount");
                        state = rs2.getString("state");

                        Loan loan = new Loan(accountNumber, amount, durationInMonths, annualInterestRate, paidAmount, state);

                        v.add(loan.getAmount());
                        v.add(loan.getDurationInMonths());
                        v.add(loan.getAnnualInterestRate());
                        v.add(loan.getTotalReturn());
                        v.add(loan.getMonthlyReturn());
                        v.add(loan.getPaidAmount());
                        v.add(loan.getRemainingAmount());
                        v.add(loan.getState());
                        
                    }
                }
            }
            df.addRow(v);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        }
        catch(Exception f){
            JOptionPane.showMessageDialog(null, f);
            System.out.println(f);
        }
    }//GEN-LAST:event_checkLoanCheckButtonActionPerformed

    private void applyLoanBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyLoanBackButtonActionPerformed
        new ClientSector().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_applyLoanBackButtonActionPerformed

    private void checkLoanBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLoanBackButtonActionPerformed
        new ClientSector().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_checkLoanBackButtonActionPerformed

    private void checkLoanCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLoanCancelButtonActionPerformed
        checkLoanUsername.setText("");
        checkLoanPassword.setText("");
        checkLoanAccountNumber.setText("");
        DefaultTableModel df2 = (DefaultTableModel) checkLoanTable.getModel();
        df2.setRowCount(0);
    }//GEN-LAST:event_checkLoanCancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static
            void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public
                    void run() {
                new LoanCheck().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyLoanBackButton;
    private javax.swing.JTextField checkLoanAccountNumber;
    private javax.swing.JButton checkLoanBackButton;
    private javax.swing.JButton checkLoanCancelButton;
    private javax.swing.JButton checkLoanCheckButton;
    private javax.swing.JButton checkLoanHomeButton;
    private javax.swing.JPasswordField checkLoanPassword;
    private javax.swing.JTable checkLoanTable;
    private javax.swing.JTextField checkLoanUsername;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
